import "./globals.css";
import "./style.css";
import Navbar from "../components/navbar.js";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  preload: false,
});

// const quicksand = Quicksand({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   preload: false,
// });

export const metadata = {
  title: "Boot.IT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
