export const competitionData = [
    {
        id: 1,
        title: "Web Innovators Challenge 2024: Ciptakan Website Masa Depan!",
        field: "Web Design",
        dateStart: "12/10/2024",
        dateEnd: "01/01/2025",
        organizer: "Universitas Negeri Surabaya",
        place: "Online",
        description: "🎉Join the Web Innovators Challenge 2024🎉 a web development competition that invites developers of all skill levels to showcase their talent and creativity! Challenge yourself to create an innovative website that is not only visually appealing but also functional and user-friendly..",
        endTime: "2024-10-12T04:10:00",
        image: "/bg6-carousel.jpg",
        link: "https://wa.me/+62"
    },
    {
        id: 2,
        title: "Cyber Shield Challenge 2025",
        field: "Cyber Security",
        dateStart: "01/11/2024",
        dateEnd: "15/11/2024",
        organizer: "Universitas Negeri Surabaya",
        place: "Online",
        description: "🎉Join the Cyber Shield Challenge 2024🎉 a cybersecurity competition that tests your skills and intelligence in protecting systems and data! Prepare yourself to face challenges that require expertise in ethical hacking, risk analysis, and defense strategies.",
        endTime: "2024-11-01T09:14:00",
        image: "/bg4-carousel.jpg",
        link: "https://wa.me/+62"
    },
    {
        id: 3,
        title: "Game Development Chalenge 2025",
        field: "Game Development",
        dateStart: "15/11/2024",
        dateEnd: "30/11/2024",
        organizer: "Universitas Negeri Surabaya",
        place: "Online",
        description: "🎉Join the Game Development Contest 2024🎉 showcase your talent in creating entertaining and innovative games! This competition is open to all developers, from beginners to professionals, who want to bring their creative ideas to life in the form of games.",
        endTime: "2024-11-15T01:10:00",
        image: "/bg5-carousel.jpg",
        link: "https://wa.me/+62"
    },
    {
        id: 4,
        title: "Artificial Intelegence Inovation Competition 2025 ",
        field: "Artificial Intelegence",
        dateStart: "31/11/2024",
        dateEnd: "10/12/2024",
        organizer: "Universitas Negeri Surabaya",
        place: "Online",
        description: "🎉Join the AI Innovation Challenge 2024🎉 a competition inviting developers, researchers, and students to explore the potential of artificial intelligence! Showcase your skills in creating innovative AI solutions that have a meaningful impact on society.",
        endTime: "2024-11-31T10:14:00",
        image: "/bg7-carousel.jpg",
        link: "https://wa.me/+62"
    },
    {
        id: 5,
        title: "Data Masters Challenge 2024 ",
        field: "Data Science",
        dateStart: "10/12/2024",
        dateEnd: "19/12/2025",
        organizer: "Universitas Negeri Surabaya",
        place: "Online",
        description: " 🎉 Data Masters Challenge 2024 🎉 Uncover Insights from Data! Join this data analysis and machine learning competition that tests your skills in extracting valuable information from data. Showcase your abilities and compete with experts in the field! Exciting Prizes: Certificates, Cash Rewards, and Opportunities for Collaboration with Leading Tech Companies. Register now and prove that you are the ultimate Data Master!",
        endTime: "2024-12-10T09:14:00",
        image: "/bg8-carousel.jpg",
        link: "https://wa.me/+62"
    },
    {
        id: 6,
        title: "IoT Innovation Challenge 2024",
        field: "Internet of Thinks",
        dateStart: "20/12/2024",
        dateEnd: "30/12/2024",
        organizer: "Universitas Negeri Surabaya",
        place: "Online",
        description: "🎉Join the IoT Device Innovation Contest 2024🎉 an event inviting innovators and developers to create Internet of Things-based solutions that can improve quality of life and enhance efficiency across various sectors! Showcase your creativity in designing innovative and practical IoT devices.",
        endTime: "2024-12-20T06:14:00",
        image: "/bg9-carousel.jpg",
        link: "https://wa.me/+62"
    },
];
