export const DataHome = {
    CardKelas: [
        {
            id: 1,
            img: "/home/Card/html-css.jpeg",
            teacher: "Hafidz Fauzan",
            title: "Basic Web Development",
            level: "Beginer",
            time: "4 hours",
            member: 200,
            modul: 10,
            rating: 4.5,
            countRating: 120,
            buy: "150.000",
            rent: "200.000"
        },
        {
            id: 2,
            img: "/home/Card/js.jpeg",
            teacher: "Nina Ria",
            title: "JavaScript Fundamentals",
            level: "Intermediate",
            time: "6 hours",
            member: 150,
            modul: 8,
            rating: 4.7,
            countRating: 95,
            buy: "180.000",
            rent: "230.000"
        },
        {
            id: 3,
            img: "/home/Card/react.jpeg",
            teacher: "Dina Sari",
            title: "Introduction to React",
            level: "Beginner",
            time: "5 hours",
            member: 300,
            modul: 12,
            rating: 4.6,
            countRating: 150,
            buy: "200.000",
            rent: "250.000"
        },
        {
            id: 4,
            img: "/home/Card/css.jpeg",
            teacher: "Arief Budi",
            title: "Advanced CSS Techniques",
            level: "Advanced",
            time: "3 hours",
            member: 100,
            modul: 5,
            rating: 4.8,
            countRating: 80,
            buy: "170.000",
            rent: "220.000"
        },
        {
            id: 5,
            img: "/Home/Card/node.jpeg",
            teacher: "Siti Maulida",
            title: "Backend with Node.js",
            level: "Intermediate",
            time: "7 hours",
            member: 220,
            modul: 9,
            rating: 4.4,
            countRating: 110,
            buy: "190.000",
            rent: "240.000"
        },
        {
            id: 6,
            img: "/Home/Card/rest api.jpeg",
            teacher: "Joko Santoso",
            title: "Building RESTful APIs",
            level: "Advanced",
            time: "5 hours",
            member: 130,
            modul: 7,
            rating: 4.6,
            countRating: 70,
            buy: "210.000",
            rent: "260.000"
        },
        {
            id: 7,
            img: "/home/Card/python.jpeg",
            teacher: "Budi Setiawan",
            title: "Data Science with Python",
            level: "Beginner",
            time: "8 hours",
            member: 180,
            modul: 6,
            rating: 4.5,
            countRating: 90,
            buy: "160.000",
            rent: "210.000"
        },
        {
            id: 8,
            img: "/Home/Card/figma.jpeg",
            teacher: "Indah Permatasari",
            title: "Web Design Principles",
            level: "Beginner",
            time: "4 hours",
            member: 160,
            modul: 8,
            rating: 4.3,
            countRating: 75,
            buy: "140.000",
            rent: "190.000"
        },
    ]
}
